package br.edu.ufape.poo.sgpa.model.enums;

public enum Segmento {
	MUSCULACAO,
    STUDIO_DE_MUSCULACAO_PERSONAL,
    CENTRO_DE_TREINAMENTO_FUNCIONAL,
    ESCOLA_DE_LUTA,
    ESCOLA_DE_DANCA,
    ESCOLA_DE_NATACAO,
    ESCOLA_DE_GINASTICA,
    STUDIO_DE_PILATES,
    STUDIO_DE_YOGA,
    BOX_CROSSFIT,
    BOX_CROSS_TRAINING,
    OUTROS;
}
